disabled_rules:
  - trailing_comma
  - todo

opt_in_rules:
  - empty_count
  - explicit_init

excluded:
  - .build
  - Generated
  - Pods
  - functions
  - docs

line_length:
  warning: 120
  error: 150

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100
