import Foundation
import SwiftUI
@preconcurrency import Vision

/// Domain model representing a detected object in the real-time detection pipeline
/// Combines YOLO detection, quality assessment, and visual fingerprinting
public struct DetectedObject: Identifiable, Equatable, Sendable {
    /// Unique identifier for this detection
    public let id: UUID

    /// Primary detected object label (e.g., "bottle", "laptop", "chair")
    public let label: String

    /// YOLO detection confidence score (0.0-1.0)
    public let confidence: Double

    /// Normalized bounding box in Vision coordinates (0.0-1.0, origin bottom-left)
    public let boundingBox: CGRect

    /// Composite quality score from ImageQualityAssessor (0.0-1.0)
    /// Threshold for automatic cataloging: 0.65
    public let qualityScore: Double

    /// Determines UI treatment and upload triggering
    /// Can be manually changed by user (e.g., double-tap to catalog)
    public var catalogMode: CatalogMode

    /// Organic subject mask for border rendering
    /// Generated by SubjectMaskGenerator using VNGenerateForegroundInstanceMaskRequest
    public let mask: VNInstanceMaskObservation?

    /// Perceptual fingerprint for deduplication
    /// Generated by ObjectDeduplicator using VNGenerateImageFeaturePrintRequest
    public let fingerprint: String

    /// Alternative label suggestions from YOLO detector
    /// Ordered by confidence, provides backup classification options
    public let alternativeLabels: [AlternativeLabel]

    /// Border color based on catalog mode
    /// - automatic: Mint green (high confidence + quality)
    /// - manual: Grey (low confidence or quality)
    /// - ignore: Not displayed to user
    public var borderColor: Color {
        switch catalogMode {
        case .automatic:
            return Color(red: 0.4, green: 0.95, blue: 0.7) // Mint green
        case .manual:
            return Color.gray.opacity(0.7)
        case .ignore:
            return Color.clear // Not displayed
        }
    }

    public init(
        id: UUID = UUID(),
        label: String,
        confidence: Double,
        boundingBox: CGRect,
        qualityScore: Double,
        catalogMode: CatalogMode,
        mask: VNInstanceMaskObservation? = nil,
        fingerprint: String,
        alternativeLabels: [AlternativeLabel] = []
    ) {
        self.id = id
        self.label = label
        self.confidence = confidence
        self.boundingBox = boundingBox
        self.qualityScore = qualityScore
        self.catalogMode = catalogMode
        self.mask = mask
        self.fingerprint = fingerprint
        self.alternativeLabels = alternativeLabels
    }

    // MARK: - Equatable Conformance

    /// Custom equality that compares all fields except mask
    /// VNInstanceMaskObservation is a class and doesn't conform to Equatable
    public static func == (lhs: DetectedObject, rhs: DetectedObject) -> Bool {
        return lhs.id == rhs.id &&
            lhs.label == rhs.label &&
            lhs.confidence == rhs.confidence &&
            lhs.boundingBox == rhs.boundingBox &&
            lhs.qualityScore == rhs.qualityScore &&
            lhs.catalogMode == rhs.catalogMode &&
            lhs.fingerprint == rhs.fingerprint &&
            lhs.alternativeLabels == rhs.alternativeLabels
        // Note: mask comparison omitted (VNInstanceMaskObservation is a class)
    }
}
